### ISSUE TITLE
SleepTK Wake features port

### ISSUE THREAD

**Issue by cyberneel** [thiswillbeyourgithub/SleepTk_pinetime_sleep_tracker#14]
@thiswillbeyourgithub I came across this from a bounty page and saw that you were more interested in the wake features than the tracking. I have a branch on my personal [repo](https://github.com/cyberneel/InfiniTime/tree/sleep-tracking-main) where I have been working on wake features more recently and got gradual wake along with snoozing to work on InfiniTime and am looking at implementing natural wake soon. I also have the framework for sleep tracking in place, just need to create the analysis part of the data. is this something you are interested in or is the bounty already taken?

**Comment by thiswillbeyourgithub** [comment]
Hi, just to reduce the chances of any other potential porter missing any information related to the bounty I will answer in issue #13 !
